# Generated by Django 4.2 on 2023-05-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0004_recipe_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="stars",
            field=models.CharField(default="4.3 stars", max_length=20),
        ),
    ]
