# Generated by Django 4.2 on 2023-05-01 21:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0008_alter_recipecomment_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipecomment",
            options={"ordering": ["-created_on"]},
        ),
    ]
