# Generated by Django 4.2 on 2023-05-02 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0010_reciperating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reciperating",
            name="stars",
        ),
        migrations.AddField(
            model_name="reciperating",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reciperating",
            name="rating",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="reciperating",
            name="comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="recipes.recipecomment",
            ),
        ),
    ]
