# Generated by Django 4.2 on 2023-05-02 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0011_remove_reciperating_stars_reciperating_owner_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reciperating",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="reciperating",
            name="rating",
        ),
        migrations.AddField(
            model_name="reciperating",
            name="stars",
            field=models.IntegerField(
                choices=[
                    (1, "1 star"),
                    (2, "2 stars"),
                    (3, "3 stars"),
                    (4, "4 stars"),
                    (5, "5 stars"),
                ],
                default=5,
            ),
        ),
        migrations.AlterField(
            model_name="reciperating",
            name="comment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="recipes.recipecomment",
            ),
        ),
    ]
